/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./../src/components/ui/button/Button.vue')['default']
    Calendar: typeof import('./../src/components/ui/calendar/Calendar.vue')['default']
    CalendarCell: typeof import('./../src/components/ui/calendar/CalendarCell.vue')['default']
    CalendarCellTrigger: typeof import('./../src/components/ui/calendar/CalendarCellTrigger.vue')['default']
    CalendarGrid: typeof import('./../src/components/ui/calendar/CalendarGrid.vue')['default']
    CalendarGridBody: typeof import('./../src/components/ui/calendar/CalendarGridBody.vue')['default']
    CalendarGridHead: typeof import('./../src/components/ui/calendar/CalendarGridHead.vue')['default']
    CalendarGridRow: typeof import('./../src/components/ui/calendar/CalendarGridRow.vue')['default']
    CalendarHeadCell: typeof import('./../src/components/ui/calendar/CalendarHeadCell.vue')['default']
    CalendarHeader: typeof import('./../src/components/ui/calendar/CalendarHeader.vue')['default']
    CalendarHeading: typeof import('./../src/components/ui/calendar/CalendarHeading.vue')['default']
    CalendarNextButton: typeof import('./../src/components/ui/calendar/CalendarNextButton.vue')['default']
    CalendarPrevButton: typeof import('./../src/components/ui/calendar/CalendarPrevButton.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    Input: typeof import('./../src/components/ui/input/Input.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./../src/components/ui/select/Select.vue')['default']
    SelectContent: typeof import('./../src/components/ui/select/SelectContent.vue')['default']
    SelectGroup: typeof import('./../src/components/ui/select/SelectGroup.vue')['default']
    SelectItem: typeof import('./../src/components/ui/select/SelectItem.vue')['default']
    SelectItemText: typeof import('./../src/components/ui/select/SelectItemText.vue')['default']
    SelectLabel: typeof import('./../src/components/ui/select/SelectLabel.vue')['default']
    SelectScrollDownButton: typeof import('./../src/components/ui/select/SelectScrollDownButton.vue')['default']
    SelectScrollUpButton: typeof import('./../src/components/ui/select/SelectScrollUpButton.vue')['default']
    SelectSeparator: typeof import('./../src/components/ui/select/SelectSeparator.vue')['default']
    SelectTrigger: typeof import('./../src/components/ui/select/SelectTrigger.vue')['default']
    SelectValue: typeof import('./../src/components/ui/select/SelectValue.vue')['default']
  }
}
