/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/book/[bookId]': RouteRecordInfo<'/book/[bookId]', '/book/:bookId', { bookId: ParamValue<true> }, { bookId: ParamValue<false> }>,
    'search': RouteRecordInfo<'search', '/book/search', Record<never, never>, Record<never, never>>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>, '/dashboard/[...all]' | '/dashboard/user' | 'add-book' | 'book-type' | 'books' | 'classify'>,
    '/dashboard/[...all]': RouteRecordInfo<'/dashboard/[...all]', '/dashboard/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'add-book': RouteRecordInfo<'add-book', '/dashboard/addBook', Record<never, never>, Record<never, never>>,
    'book-type': RouteRecordInfo<'book-type', '/dashboard/book-type', Record<never, never>, Record<never, never>>,
    'books': RouteRecordInfo<'books', '/dashboard/bookManager', Record<never, never>, Record<never, never>>,
    'classify': RouteRecordInfo<'classify', '/dashboard/classify', Record<never, never>, Record<never, never>>,
    '/dashboard/user': RouteRecordInfo<'/dashboard/user', '/dashboard/user', Record<never, never>, Record<never, never>>,
    'home': RouteRecordInfo<'home', '/home', Record<never, never>, Record<never, never>, '/home/indexPage'>,
    '/home/indexPage': RouteRecordInfo<'/home/indexPage', '/home/indexPage', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'personal-center': RouteRecordInfo<'personal-center', '/personal-center', Record<never, never>, Record<never, never>, '/personal-center/address' | '/personal-center/favorites' | '/personal-center/orders'>,
    '/personal-center/address': RouteRecordInfo<'/personal-center/address', '/personal-center/address', Record<never, never>, Record<never, never>>,
    '/personal-center/favorites': RouteRecordInfo<'/personal-center/favorites', '/personal-center/favorites', Record<never, never>, Record<never, never>>,
    '/personal-center/orders': RouteRecordInfo<'/personal-center/orders', '/personal-center/orders', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/user': RouteRecordInfo<'/user', '/user', Record<never, never>, Record<never, never>>,
  }
}
